### ISSUE TITLE
Add demographic data files/shapefiles?

### ISSUE THREAD

**Issue by sdwfrost** [konswells1/COVID19-LSOA-metapopulation-model#1]
Hi @konswells1!

This looks really nice; is it possible to add the demographic data and shapefiles to this so that the model can be run?

**Comment by konswells1** [comment]
Thanks, @sdwfrost! Data file with demographic data and geographical coordinates added. Shapefile is too large for upload but not required for running the model.

**Comment by sdwfrost** [comment]
Thanks! Could you also add `Rural_Urban_Classification__2011__of_Lower_Layer_Super_Output_Areas_in_England_and_Wales.csv`?

**Comment by konswells1** [comment]
OK, added!

**Comment by sdwfrost** [comment]
Great! Closing this issue now.
