### ISSUE TITLE
Gravity model based on 9, not 10, nearest neighbours?

### ISSUE THREAD

**Issue by sdwfrost** [konswells1/COVID19-LSOA-metapopulation-model#3]
In the loop generating `GravDist.lsoa`, there are these lines:

```r
#Distance to 10 nearest populations
popnearest.10_dist <- sort(Dist.lsoa[i,])[2:10]
```

Although the comment says 10 nearest populations, `popnearest.10_dist` is based on 9 nearest neighbours.

**Comment by konswells1** [comment]
corrected to "popnearest.10_dist <- sort(Dist.lsoa[i,])[2:11]" (matching also the code in the simulation loop were the subest of 10 nearest populations is correctley selected as "sort(Dist_sel[i,])[2:11]"
