### ISSUE TITLE
Missing libraries/variables

### ISSUE THREAD

**Issue by sdwfrost** [konswells1/COVID19-LSOA-metapopulation-model#4]
- Use of `brewer.pal` requires `library(RColorBrewer)`
- `dir_UK.geo` is not defined

**Comment by konswells1** [comment]
“setwd(dir_UK.geo)” deleted and call brewer.pal() deleted (not required to run code)

**Comment by sdwfrost** [comment]
Thanks @konswells1! These libraries are also not loaded, but required for the code to run:

```r
library(ggplot2)
library(igraph)
library(network)
```
